# Generated by Django 2.0 on 2018-06-27 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0003_userleavingmessage_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='上传的文件', upload_to='message/files/', verbose_name='上传的文件')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': 'app 信息',
                'verbose_name_plural': 'app 信息',
            },
        ),
    ]
